### ISSUE TITLE
Package install failing with Yarn due to non-semver compliant versioning

### ISSUE THREAD

**Issue by HeberLZ** [ilkkao/co-mocha#6]
Hi,

The semver spec specifies that stuff after a hyphen is a prerelease version:

> A pre-release version MAY be denoted by appending a hyphen and a series of dot separated identifiers immediately following the patch version
> Precedence refers to how versions are compared to each other when ordered. [...] When major, minor, and patch are equal, a pre-release version has lower precedence than a normal version. Example: 1.0.0-alpha < 1.0.0

Because of this, when trying to install gulp-co-mocha with yarn, as the dependency to this module is defined as ^1.17.1-co.1, it ends up resolving to 1.17.1 which is a broken build, because it considers ^1.17.1-co.1 a pre-release due to the hyphen.

Is it possible to release the current build as 1.17.2 in order to ask the maintainer of gulp-co-mocha to fix it on their layer too?

PS: Before i came here i created an issue on yarn's repo https://github.com/yarnpkg/yarn/issues/1545

Cheers!

**Comment by ilkkao** [comment]
Hi @HeberLZ 

Sorry for the huge delay. I just release 1.17.2 as you requested.
